@startuml
'https://plantuml.com/class-diagram

fflib_ISObjectUnitOfWork <|-- fflib_SObjectUnitOfWork : implements

interface fflib_ISObjectUnitOfWork{
void registerNew(SObject record)
void registerNew(List<SObject> record)
void registerNew(Sobject record, Schema.SObjectField relatedToParentField, SObject relatedToParentRecord)
void registerRelationship(SObject record, Schema.SObjectField relatedToParentField, SObject relatedTo)
void registerRelationship(Messaging.SingleEmailMessage email, SObject relatedTo)
void registerRelationship(SObject record, Schema.SObjectField relatedToField, Schema.SObjectField externalIdField, Object externalId)
void registerDirty(SObject record)
void registerDirty(List<SObject> records, List<SObjectFields> dirtyFields)
 void registerDirty(SObject record, List<SObjectField> dirtyFields)
  void registerDirty(SObject record, Schema.SObjectField relatedToParentField, SObject relatedToParentRecord)
 void registerDirty(List<SObject> records)
 void registerEmptyRecycleBin(SObject record)
  void registerUpsert(SObject record)
  void registerUpsert(List<SObject> records)
  void registerDeleted(SObject record)
  void registerDeleted(List<SObject> records);
  void registerPermanentlyDeleted(List<SObject> records)
  void registerPermanentlyDeleted(SObject record)
  void registerPublishBeforeTransaction(SObject record)
   void registerPublishBeforeTransaction(List<SObject> records)
   void registerPublishAfterSuccessTransaction(SObject record)
   void registerPublishAfterSuccessTransaction(List<SObject> records)
   void registerPublishAfterFailureTransaction(SObject record)
   void registerPublishAfterFailureTransaction(List<SObject> records)
   void registerWork(fflib_SObjectUnitOfWork.IDoWork work)
   void registerEmail(Messaging.Email email);
}

class fflib_SObjectUnitOfWork{}

interface fflib_IUnitOfWorkFactory{
fflib_ISObjectUnitOfWork newInstance()
	fflib_ISObjectUnitOfWork newInstance(fflib_SObjectUnitOfWork.IDML dml)
	fflib_ISObjectUnitOfWork newInstance(List<SObjectType> objectTypes)
	fflib_ISObjectUnitOfWork newInstance(List<SObjectType> objectTypes, fflib_SObjectUnitOfWork.IDML dml)
}
@enduml